<?php
/*
 * $Id$
 */


define ('TM_ROOT_URL', 'civicrm/tm');

require 'functions.php';

/**
 * Implementation of hook_init()
 */
function tmcivi_init() {
  _tmcivi_initialize();
}

/**
 * Implementation of hook_perm()
 */
function tmcivi_perm() {
  $perms = array(
    'access tmcivi',
    'administer tmcivi',
  );

  return $perms;
}

/* Implementation of hook_civicrm_config
 */
function tmcivi_civicrm_config( &$config ) {
  _tmcivi_initialize();
}

/* Implementation of hook_civicrm_xmlMenu
 */
function tmcivi_civicrm_xmlMenu( &$files ) {
  $files[] =
    drupal_get_path('module', 'tmcivi') . DIRECTORY_SEPARATOR .
    'civicrm_xmlMenu.xml';
}

/*
 * Implementation of hook_civicrm_pageRun
 */
function tmcivi_civicrm_pageRun(&$page) {
  // Include any like-named js and css files.
  _tmcivi_include_resources($page->getVar('_name'));
}

/**
 * Implementation of hook_tmcivi_template_dir
 */
function tmcivi_tmcivi_template_dir() {  
  return _tmcivi_root_path() . DIRECTORY_SEPARATOR . 'Smarty/templates';
}

/**
 * Implementation of hook_tmcivi_plugins_dir
 */
function tmcivi_tmcivi_plugins_dir() {
  return _tmcivi_root_path() . DIRECTORY_SEPARATOR . 'Smarty/plugins';
}

/**
 * Implementation of hook_tmcivi_custom_php_dir
 */
function tmcivi_tmcivi_class_dir() {
  return _tmcivi_root_path() . '/class';
}

/**
 * Implementation of hook_enable()
 */
function tmcivi_enable() {
  // invoke civicrm menu rebuild, as we're adding some civicrm paths
  civicrm_initialize( );
  require_once 'CRM/Core/Menu.php';
  CRM_Core_Menu::store( );
}

/**
 * Implementation of hook_tmcivi_path
 */
function tmcivi_tmcivi_path() {
   $paths['raw'] = _tmcivi_root_path() . '/class/TM/Raw/Raw';
}